# Generated by Django 3.1.7 on 2021-03-23 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=10)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.usertodo')),
            ],
        ),
    ]
